export const INSURERS = [
  "Nepal Micro",
  "Protective",
  "Star Micro",
  "Trust Micro",
  "Nepal",
  "The Oriental",
  "National",
  "Himalayan Everest",
  "United Ajod",
  "Neco",
  "Sagarmatha Lumbini",
  "Prabhu",
  "IGI Prudential",
  "Shikhar",
  "NLG",
  "Siddhartha",
  "Rastriya Beema",
  "Sanima GIC",
] as const;
